name: Main Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: |
        ./gradlew build jacocoTestReport
        ./gradlew benchmarks:build

    - name: Report to Codecov
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
